name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: cp package.json dist/package.json
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: larp-bugle-bot-endpoint
          runtime: nodejs14
          credentials: ${{ secrets.gcp_credentials }}
          source_dir: dist
          region: europe-central2
          entry_point: botFunction

